### ISSUE TITLE
DE Australia - Aug-Sep 21 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#103]
### Release checklist: 
- [x] Help workflow - Clip and Ship - https://github.com/TerriaJS/de-australia-map/issues/92
- [x] Catalogue - finalise structure, names etc https://github.com/TerriaJS/de-australia-map/issues/93
- [x] story loses pop up chart (feature info) https://github.com/TerriaJS/de-australia-map/issues/97
- [x] dots bug https://github.com/TerriaJS/de-australia-map/issues/72 + config change needed after update to latest TerriaJS
- [x] https://github.com/TerriaJS/de-australia-map/issues/104
________________________________________________________________________________________________________________________________________

### Configuration changes reminder: 

- [x] after this PR is merged https://github.com/TerriaJS/terriajs/pull/5760 - configuration changes are needed on the production site to fix the charts

**Comment by na9da** [comment]
- [x] Adding this issue to fix delta tool - https://github.com/TerriaJS/terriajs/issues/5762

**Comment by nf-s** [comment]
in test https://de-australia.test.saas.terria.io/

**Comment by nf-s** [comment]
- [x] Need to add configuration to fix charts  (already done in dev+test)

```json
{
  "catalog": [
  {
      "type": "wms",
      "name": "DEA Waterbodies",
      "url": "https://hotspots.dea.ga.gov.au/geoserver/public/wms",
      "chartDisclaimer": "Digital Earth Australia Waterbodies shows the wet surface area of waterbodies as estimated from satellites. It does not show depth, volume, purpose of the waterbody, nor the source of the water. <br> For more detailed information see <a href='https://www.ga.gov.au/dea/products/dea-waterbodies'>https://www.ga.gov.au/dea/products/dea-waterbodies</a>",
      "layers": "DigitalEarthAustraliaWaterbodies",
      "featureInfoTemplate": {
        "template": "<div style='width:600px'><h3>Waterbody Identifier: {{uid}}<br /> Percentage of surface area (not volume) observed as wet</h3><br/><chart chart-glyph-style='circle' chart-type='lineAndPoint' id='{{uid}}' title='Waterbody {{uid}}' preview-x-label='Date' sources='{{#terria.urlEncode}}{{timeseries}}{{/terria.urlEncode}}'  column-names='Time,Percentage of total surface area (not volume) observed as wet,Wet Pixel Count' column-units='Date of satellite observation,%,#'></chart>{{>disclaimer}}</div>",
        "partials": {
          "disclaimer": "This graph shows the wet surface area of waterbodies as estimated from satellites. It does not show depth, volume, purpose of the waterbody, nor the source of the water. <br> For more detailed information see https://www.ga.gov.au/dea/products/dea-waterbodies."
        }
      },
      "id": "DGGjbr",
      "shareKeys": [
        "Root Group/Surface Water/Digital Earth Australia Waterbodies/Digital Earth Australia Waterbodies"
      ]
    },
    {
      "type": "wms",
      "name": "DEA Surface Reflectance (Sentinel-2A MSI)",
      "url": "https://ows.dea.ga.gov.au/",
      "opacity": 1,
      "layers": "s2a_ard_granule_nbar_t",
      "linkedWcsUrl": "https://ows.dea.ga.gov.au/",
      "linkedWcsCoverage": "s2a_ard_granule_nbar_t",
      "chartColor": "white",
      "timeFilterPropertyName": "data_available_for_dates",
      "availableDiffStyles": ["ndvi", "ndwi", "mndwi", "nbr"],
      "leafletUpdateInterval": 750,
      "chartType": "momentPoints",
      "chartGlyphStyle": "wye",
      "featureInfoTemplate": {
        "template": "<table>  <tr><td><b>Time</b></td><td>{{data.0.time}}</td></tr>  <tr><td><b>Narrow Blue - 440</b></td><td>{{data.0.bands.nbar_coastal_aerosol}}</td></tr>  <tr><td><b>Blue - 490</b></td><td>{{data.0.bands.nbar_blue}}</td></tr>  <tr><td><b>Green - 560</b></td><td>{{data.0.bands.nbar_green}}</td></tr>  <tr><td><b>Red - 670</b></td><td>{{data.0.bands.nbar_red}}</td></tr>  <tr><td><b>Vegetation Red Edge - 710</b></td><td>{{data.0.bands.nbar_red_edge_1}}</td></tr>  <tr><td><b>Vegetation Red Edge - 740</b></td><td>{{data.0.bands.nbar_red_edge_2}}</td></tr>  <tr><td><b>Vegetation Red Edge - 780</b></td><td>{{data.0.bands.nbar_red_edge_3}}</td></tr>  <tr><td><b>Near Infrared (NIR) - 840</b></td><td>{{data.0.bands.nbar_nir_1}}</td></tr>  <tr><td><b>Narrow Near Infrared - 870</b></td><td>{{data.0.bands.nbar_nir_2}}</td></tr>  <tr><td><b>Shortwave Infrared (SWIR) - 1610</b></td><td>{{data.0.bands.nbar_swir_2}}</td></tr>  <tr><td><b>Shortwave Infrared (SWIR) - 2190</b></td><td>{{data.0.bands.nbar_swir_3}}</td></tr>  <tr><td><b>NDVI - Red, NIR</b></td><td>{{data.0.band_derived.ndvi}}</td></tr>  <tr><td><b>NDWI - Green, NIR</b></td><td>{{data.0.band_derived.ndwi}}</td></tr><tr><td><b>MNDWI - Green, NIR</b></td><td>{{data.0.band_derived.mndwi}}</td></tr><tr><td><b>NDCI - Red Edge, Red</b></td><td>{{data.0.band_derived.ndci}}</td></tr></table><p><chart id='{{lat}}{{lon}}{{data.0.time}}' title='NBAR at {{lat}},{{lon}}' column-units='Wavelength (nm), Reflectance x 10k' preview-x-label='NBAR Reflectance'>nm,NBAR Reflectance\n440,{{data.0.bands.nbar_coastal_aerosol}}\n490,{{data.0.bands.nbar_blue}}\n560,{{data.0.bands.nbar_green}}\n670,{{data.0.bands.nbar_red}}\n710,{{data.0.bands.nbar_red_edge_1}}\n740,{{data.0.bands.nbar_red_edge_2}}\n780,{{data.0.bands.nbar_red_edge_3}}\n840,{{data.0.bands.nbar_nir_1}}\n870,{{data.0.bands.nbar_nir_2}}\n1610,{{data.0.bands.nbar_swir_2}}\n2190,{{data.0.bands.nbar_swir_3}}</chart></p><p><b>Imagery available for dates:</b>{{#data_available_for_dates}}<br/>{{.}}{{/data_available_for_dates}}</p>",
        "formats": {
          "lat": {
            "maximumFractionDigits": 5
          },
          "lon": {
            "maximumFractionDigits": 5
          }
        }
      },
      "tileErrorHandlingOptions": {
        "ignoreUnknownTileErrors": true
      },
      "id": "iNJKMD",
      "shareKeys": [
        "Root Group/Satellite images/Satellite images 10m - daily/Sentinel 2 satellite imagery archive/Sentinel 2a satellite images"
      ]
    }
  ]
}
```

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/137058028-d4a4c233-3573-4310-ba5e-6dbcac2882ea.png)


https://de-australia.test.saas.terria.io/#share=s-jYs2Ye6liEwHSUH3LP4bwVgXpCs

**Comment by nf-s** [comment]
All done - now in dev + test

**Comment by AnaBelgun** [comment]
Configuration updated by DEA team on 18 Oct 2021
