### ISSUE TITLE
DE Australia - Oct 19 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#13]
- [x] workbench user stepping guide - https://github.com/TerriaJS/terriajs/pull/3743 
with this, once the modal is created on front page, the "take a tour" button will have to point to the Help & FAQ pages because it cannot copy the video button from DE Africa (that video will be very specific to Africa map)

- [x] update related maps - https://github.com/TerriaJS/de-australia-map/issues/15

- [x] add data = explore data: https://github.com/TerriaJS/terriajs/pull/3742 and https://github.com/terriajs/terriajs/issues/3707

- [x] redraft and include dea email address on feedback form https://github.com/TerriaJS/de-australia-map/issues/16

- [x] Leaflet fix - TerriaJS/terriajs#3740

- [x] update DNS - https://github.com/TerriaJS/de-australia-map/pull/18

- [x] logos - https://github.com/TerriaJS/de-australia-map/issues/7

- [x] about pages - https://github.com/TerriaJS/de-australia-map/issues/6 

- [x] data and metadata - https://github.com/TerriaJS/de-australia-map/issues/8

- [x] help menu button to point to help and FAQ - https://github.com/TerriaJS/de-australia-map/issues/14

- [ ] social media links in about pages - https://github.com/terriajs/de-australia-map/issues/19 - only if time permits

**Comment by soyarsauce** [comment]
- [ ] merge in https://github.com/TerriaJS/de-australia-map/pull/20 (for language overrides, once terriajs has been released past 7.7.0)
