### ISSUE TITLE
TerriaJS Onboarding v2

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/de-australia-map#41]
#### so I can get started using a given TerriaMap (DEA Aust/Africa)

Other notes from Vic:
>We felt the first step to fixing the on-boarding experience was leaning up the UI so its a little easier to understand, especially for first time users. I tried not to go too far with my designs and so more of a clean up. This is by no mens perfect or the ideal layout but I feel it is an improvement. Please note that when I do the actual on-boarding screens such as modal disclaimer & help, the layout may need to some tweaks.

Design discussion ticket at https://github.com/TerriaJS/de-australia-map/issues/39

Gdrive notes: https://docs.google.com/document/d/1cENE8rKUDknTd5EY9NzplAghaV4FetJij-UwIgX2AtU/edit?folder=17hIu2s1LGi2semARtA6h79yBsls3HtxM

Based on designs: https://projects.invisionapp.com/share/VQWC0P9FC3D

On - boarding (4ish) pieces:
- Disclaimer: https://github.com/terriajs/terriajs/issues/4181

- Welcome: https://github.com/terriajs/terriajs/issues/4180

- Tour: https://github.com/terriajs/terriajs/issues/4183

- Help: https://github.com/terriajs/terriajs/issues/4182
  - We need a help-content-strategy: X # of 
  - Merge "getting started" with "how it works". Have a default, generic video with main functions of any terria map, put it into the default "how it works/getting started", put the "list menu" design underneath the video (@alyce)

(Unrelated to this ticket splitter notes)
- continue designing split. req for feedback.
- in the meantime, for delta, leave splitter as it is, re-wire delta to use a hybrid solution of deltav2 and delta v2.5(20200330 Sprint planning vic-demo)

Remaining things from closed v2 tickets:

- [ ] [Relevant docs are updated] item for help panel https://github.com/TerriaJS/terriajs/issues/4182
- [ ] [Relevant docs are updated] item for disclaimer https://github.com/TerriaJS/terriajs/issues/4181
- [ ] https://github.com/TerriaJS/terriajs/issues/4353

**Comment by soyarsauce** [comment]
Help panel items.

For DEA
- "getting started" is a video, the first item.
- satellite imagery exploration as second item (can be a video or a tour type of thing) - use existing satellite imagery guide for now.


For the two videos,
- generic "how to interact with satellite imagery", which includes splitter help.
under the help menu in satellite imagery, do we use the video or tour bits, or both?

When you click satellite imagery, just expand the guide directly?
Just don't use video for satellite imagery?

**Comment by soyarsauce** [comment]
19th.
Tester goes in. Opens terria-cube (no DE africa map)

Gets in front of terria-cube with mobx, w/ all satellite imagery from DEA*2

It will have on the landing page.
Disclaimer(terria-cube). Acknowledge,
Get to getting started modal.

Paths:
- I'll need some help
List of generic items, including - getting started, satellite imagery, 

++ Delta catalog


Dive into catalog, onboarding ends here.

When they ~click satellite imagery.~ add a satellite imagery dataset 
> When you click satellite imagery, just expand the guide directly?
Crispy: or modal-in-form-of-tour.

**Comment by AnaBelgun** [comment]
This epic is superseded by Onboarding v3 https://github.com/TerriaJS/terriajs/issues/4391; should any tickets remain after June 30, they will be transferred to a new User guides and onboarding generic epic
