### ISSUE TITLE
DE Australia on MobX- June 2020 release - End of FY20 delivery 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#47]
Acceptance criteria for update of DE Australia to MobX TerriaJS: 

- [x] Application available for testing at a new distinct DE Australia-on-MobX url 

- [x] Data catalogue available in MobX map: 61 datasets in 29 groups

- [ ] geojson catalog items converted to mobx-catalogs

- [ ] Specific to DEA: Waterbodies charts display the same behaviour and warning message: http://de-australia.terria.io/#share=s-q2fCou4W0OVpWyZXUBkzqvFvnJz

- [x] Specific to DEA: Show satellite imagery as dots on the charts of Water regulations data (BoM) http://de-australia.terria.io/#share=s-dcJhodA74cvLC7tHvuR78rUqq9I
- This will work once we set the trait

- [ ] Availability of Delta functionality working with both DE OWS and NCI GSKY service implementation 

- [x] Include Delta v2 available on test site: https://tc-user-testing.terria.io/ 

Development to support the above:

- [x] SOS on MobX TerriaJS/terriajs#3896 and PR TerriaJS/terriajs#4167
    - [x] Port SOS
    - [x] ~To confirm with Nanda that Mode 2 ("fetching features and observation data together.") is not needed~

- [x] Timeseries on MobX - TerriaJS/terriajs#4226

- [x]  Clip and ship (TBC) - TerriaJS/terriajs#4340; PR https://github.com/TerriaJS/terriajs/pull/4461 - Crispy to review

- [x] Implement dots on charts to show imagery (currently implemented as lines) - https://github.com/TerriaJS/de-australia-map/issues/48

- [ ] Copy implementation of warning message when opening waterbodies and click on expand chart - https://github.com/TerriaJS/de-australia-map/issues/49; needs this: https://github.com/TerriaJS/terriajs/pull/4479/ 

- [x] themeying - https://github.com/TerriaJS/terriajs/pull/4480 
- [x] (merge theme-ing into mobx, but for now it is released off a branch)

Post 30 June - to release 30 June - 15 July 2020
----------------------------------------------------------------------------------------------------------
- [ ] Delta v3 implementation - post user testing undertaken 19-21/05/2020 - https://github.com/TerriaJS/terriajs/issues/4390

- [ ] Delta v3 - has to work with ODC DEA OWS set up as well as with NCI GSKY service

**Comment by soyarsauce** [comment]
Re: 61 datasets in 29 groups - that's just to say we ensure the same catalog is available on DE Australia mobx, right?

**Comment by soyarsauce** [comment]
re: above
>Ana Belgun  10:49 AM
yes

**Comment by soyarsauce** [comment]
> Waterbodies charts display
 ana: leave this as last prio

**Comment by soyarsauce** [comment]
Most of this is done now:
http://de-australia.saas.terria.io/

**Comment by soyarsauce** [comment]
Includes the DE aust themeing, but help content to be updated

**Comment by soyarsauce** [comment]
@steve9164 to pull in terraicube catalogs too

**Comment by AnaBelgun** [comment]
@soyarsauce @steve9164 why do we need the terriacube catalogue? unless I'm misunderstanding; the terria cube has a lot of stuff which is in development / experimentation and shouldn't be in DEA
unless you refer to the data for Delta 2

**Comment by soyarsauce** [comment]
@AnaBelgun in your checklist, there is ` Show satellite imagery as dots on the charts of Water regulations data (BoM)` which comes from a terria-cube catalog item

**Comment by steve9164** [comment]
@AnaBelgun There's a catalogue file that is loaded by production Digital Earth Australia that is named `terria-cube.json`. It has only the Water Regulations data in it, the rest comes from a catalogue file called `dea.json` which is managed by GA. It's completely separate from the catalogue of terriacube, it's just poorly named.

That small catalogue file is what Wing is referring to, and Wing will include that in the release.

**Comment by AnaBelgun** [comment]
This has been released and sent to client on 30 June. 
Outstanding issues (waterbodies charts banner and delta v3) are included in the next release: https://github.com/TerriaJS/de-australia-map/issues/52
