### ISSUE TITLE
DE Australia - Feb 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#74]
This ticket will incorporate feedback from migration testing post 24/12/2020 and other outstanding issues. 

- [x] Delta date label wrong - https://github.com/terriajs/terriajs/issues/5236 https://github.com/TerriaJS/terriajs/pull/5248
- [x] Waterbodies - hide some CSV rows - https://github.com/TerriaJS/de-australia-map/issues/71 - done, merged
- [x] Waterbodies - dots on charts - https://github.com/TerriaJS/de-australia-map/issues/72 - done, merged 
- [x] update to latest TerriaJS next 

Post Feb 21 release of saas version 
_______________________________________________________________________________________________________________________________________
- [ ] wrong email in terrain server - https://github.com/TerriaJS/de-australia-map/issues/67 **this is for v7 - not v8**

**Comment by nf-s** [comment]
- [ ] set  the 2d view as default and straighten the zoom area when landing for DE Africa

**Comment by nf-s** [comment]
https://beta.de-australia.terria.io/ Updated

**Comment by nf-s** [comment]
I'm going to close this, as v8 SaaS has been updated.
