### ISSUE TITLE
DE Australia - Mar 21 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#77]
- [x] Google analytics set up https://github.com/TerriaJS/de-australia-map/issues/76
- [x] UX research summary #80 
- [x] splitter is fixed: https://github.com/TerriaJS/terriajs/issues/5370
- [x] sharing is fixed: https://github.com/TerriaJS/terriajs/issues/5300

Robbi (DEA team) is preparing the Coastal erosion story for launch by Minister between 12- 16 April (exact date TBC).  

DEA team has prepared a change to the Coastlines data needed for the launch. 
Here are the changes to config file: https://www.dropbox.com/s/lhlh0xtxkq73wxn/deacoastlines_v8_revised.json?dl=1

The share url also needs to be manually set up as: https://maps.dea.ga.gov.au/#share=s-DEACoastlines

**Comment by AnaBelgun** [comment]
Done.
