### ISSUE TITLE
DE Australia - Apr 2021 release 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#85]
- [ ] Story: start design and planning of story v2.0 - https://github.com/TerriaJS/terriajs/issues/3532
- [x] Help pop up (bottom right corner): https://github.com/TerriaJS/de-australia-map/issues/87
- [ ] Tool Tips: edit text - https://github.com/TerriaJS/de-australia-map/issues/88 
- [ ] migrate Terria Cube to v8 - @nf-s

**Comment by AnaBelgun** [comment]
this ticket is superseded by May release; some things are not dependent on the release (i.e. tool tips)
