### ISSUE TITLE
DE Australia - Jul 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#86]
- [x] Help workflow Compare - https://github.com/TerriaJS/de-australia-map/issues/89
- [x] Help workflow Difference - https://github.com/TerriaJS/de-australia-map/issues/90
- [x] Help workflow - Water + satellite - https://github.com/TerriaJS/de-australia-map/issues/91
- [x] Catalogue - finalise structure, names etc https://github.com/TerriaJS/de-australia-map/issues/93
- [x] NEII Feature - Obs dates - finalise https://github.com/TerriaJS/de-australia-map/issues/94
- [x] Custom google analytics - https://github.com/TerriaJS/de-australia-map/issues/95
- [x] Add Collections 3 - https://github.com/TerriaJS/de-australia-map/issues/101 - as part of catalogue restructure

**Comment by AnaBelgun** [comment]
released new catalogue
